apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  namespace: demoapp
  labels:
    app: frontend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      version: v1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
        - name: frontend
          image: hulk18/frontend:v1.0.0
          env:
            - name: API_URL
              value: http://backend.demoapp.svc.cluster.local
          ports:
            - containerPort: 3000
