apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: demoapp
spec:
  selector:
    app: frontend
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
