apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
  namespace: demoapp
  labels:
    app: backend
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      version: v1
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
        - name: backend
          image: hulk18/backend:v1.0.0
          ports:
            - containerPort: 8080
