apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  namespace: demoapp
  labels:
    app: backend
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      version: v2
  template:
    metadata:
      labels:
        app: backend
        version: v2
    spec:
      containers:
        - name: backend
          image: hulk18/backend:v2.0.0
          ports:
            - containerPort: 8080
